# Generated by Django 5.0 on 2023-12-21 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_evento',
            field=models.DateTimeField(verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Evento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo do Evento'),
        ),
    ]
